# FIXME: This doesn't seem to be used
v6_set_switchbot_curtain_cover_position:
  description: Sets cover position with ability to set speed
  fields:
    entity_id:
      description: The cover to adjust
      selector:
        entity:
          domain: cover
          multiple: true
    speed:
      description: transition speed
      selector:
        number:
          min: 1
          max: 255
    position:
      description: desired position
      selector:
        number:
          min: 0
          max: 100
