name: Validate with hassfest

on:
  push:
    branches:
      - '!master'  # Not tuned enough to allow running in master.
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"

